### PR TITLE
Fixing things

### PR DESCRIPTION
**Pull request by rasmusolle**

### CODE REVIEW

**Comment by rasmusolle** [comment]
So more people can join

**Comment by Hetal728** [comment]
More like people that can't buy the game can join

**Comment by UclCommander** [comment]
-1

**Comment by Hetal728** [comment]
<b>test<b>

**Comment by Hetal728** [comment]
@rasmusolle You do realize that making the server offline allows both the Spigot team AND Mojang not offer support to me/community

**Pull request closed without merging**
